name: Publish to Hex

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  publish:
    name: Publish to Hex

    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Erlang and Elixir
        uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: "29.0"
          elixir-version: "1.20"

      - name: Fetch dependencies
        run: mix deps.get

      - name: Publish to Hex
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
