name: Publish to Hex

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  publish:
    name: Publish to Hex

    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Erlang and Elixir
        uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
        with:
          otp-version: "27.2"
          elixir-version: "1.18"

      - name: Fetch dependencies
        run: mix deps.get

      - name: Publish to Hex
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
